### ISSUE TITLE
Multiple overlay demo, under jQuery Tools 1.2.6 / jQuery 1.6.2

### ISSUE THREAD

**Issue by alibby251** [jquerytools/www#14]
The standalone (and I think the homepage?) demo is broken - it doesn't show the CSS correctly.

There is a missing CSS link that needs to be added to the demo.

**Comment by alibby251** [comment]
The changes required:
1. Drop this:
   
   
2. Replace it with this:
   
   <style>
   
   /* overlay */
   .overlay, #overlay {
       padding:40px;
       width:576px;
       display:none;
       background-image:url(http://www.flowplayer.org/tools/img/overlay/white.png);
   }
   
   a.close {
       background:url(http://www.flowplayer.org/tools/img/overlay/close.png) no-repeat;
       position:absolute;
       top:2px;
       right:5px;
       width:35px;
       height:35px;
       cursor:pointer;
   }
   
   #overlay_player {
       display:block;
       height:450px;
   }
   
   
   /* override default settings */
   div.overlay {
       width:400px;
       height:250px;
   }
   </style>

**Comment by bradrobertson** [comment]
added in the overlay-minimal.css,  hopefully fixes this on next www deploy
