### ISSUE TITLE
Website Inconsistency - Need to switch class names on Tabs Slideshow Page

### ISSUE THREAD

**Issue by alibby251** [jquerytools/www#16]
Not sure if I would classify this as a bug, but I did notice that there is a small error in your documentation on the website in regards to the Tabs Slideshow plugin page: http://flowplayer.org/tools/demos/tabs/slideshow.html

The page example uses "next" and "prev" classes for the arrows that allow you to switch between tabs, but the standalone version uses "forward" and "previous" classes for the arrows. I tried both and the correct default behavior is the "forward" and "previous" classes, so you should probably switch the demo example on the home page.

-Paul

**Comment by alibby251** [comment]
Raised by paultannenbaum on the library repo, as issue 330.

**Comment by bradrobertson** [comment]
fixed, thx!
