### ISSUE TITLE
http://flowplayer.org/tools/demos/overlay/multiple.htm

### ISSUE THREAD

**Issue by alibby251** [jquerytools/www#20]
The demo example http://flowplayer.org/tools/demos/overlay/multiple.htm seems messed up in Firefox and IE

**Comment by alibby251** [comment]
Raised by ppailes from the main repo area.

**Comment by bradrobertson** [comment]
Messed up on all browsers due to missing css file.  I've added it to www, hopefully on next deploy that should fix things.
