### ISSUE TITLE
confusing documentation for overlay

### ISSUE THREAD

**Issue by alibby251** [jquerytools/www#21]
Hi, I'd like to report that I've lost a couple of hours trying to figure out a problem I was having with the documentation of the overlay. Documentation says overlay may be positioned either through percentage or pixels. Example given is '10%'. However, no example of pixels is given. I assumed I needed to provide the CSS textual value, '50px'. This wouldn't work. I didn't realize I should have provided just the integer value.

**Comment by alibby251** [comment]
Raised by thujone on the main github area.

**Comment by bradrobertson** [comment]
> Specifies how far from the top edge of the screen the overlay should be placed. Acceptable values are an integer number specifying a distance in pixels, a string (such as '15%') specifying a percentage value or "center" in which case the overlay is vertically centered. Percentage values work consistently at different screen resolutions.

Wouldn't have though you could get much clearer than "an integer number", but I added an example and bolded 'integer number' so there is no confusion

**Comment by alibby251** [comment]
Yeah, ordinarily I would agree, but I think the issue was down to 
whether it needed the "px" afterwards, as stating that an integer number 
could just mean a number on its own to some people, and not know that it 
needs the "px" afterwards. As long as there is an example there, then 
that's fine.

**Comment by bradrobertson** [comment]
Ya but in this case it actually DOES require a NUMBER for pixel based dimensions, not a string.  I've put in an example either way so hopefully that clears it up.
