### ISSUE TITLE
custom tools downloader seems broken

### ISSUE THREAD

**Issue by tvon** [jquerytools/www#3]
I get a 404 when selecting custom components and attempting to download, eg just 'overlay' and 'expose':

http://flowplayer.org/tools/download/combine/1.2.5/jquery.tools.min.js?download=true&t=overlay&t=toolbox.expose

**Comment by daytonn** [comment]
It appears to break when selecting the form tools. I can successfully download any combination except ones including the form tools.

**Comment by tvon** [comment]
The link I provided now works, so it appears to be an inconsistant problem.

**Comment by molte** [comment]
It returns a 404 error for me when trying the following setup:
http://flowplayer.org/tools/download/combine/1.2.5/jquery.tools.min.js?download=true&t=tooltip&t=tooltip.dynamic&t=overlay&t=overlay.apple&t=toolbox.expose&t=toolbox.mousewheel
